name: Deploy to AWS

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest #Github hosted ubuntu runner name

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 #This name is available in Github actions documentation. Search for the name for each task and update here

      - name: Running commands on runner machine
        run: | # | pipe symbol is used for running multiple commands
          echo "Hello World"
          ls -al 
          pwd
          touch hello.txt
